import type { Metadata } from "next";
import { Preahvihear } from "next/font/google";
import "./globals.css";

import ClientWrapper from "@/components/layout/ClientWrapper";



const preahvihear = Preahvihear({
  weight: ["400"],
  variable: "--font-Preahvihear",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Newtons Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${preahvihear.variable}`}>
      <body className="antialiased min-h-screen bg-[#000000]">
       
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
               <ClientWrapper>    {children} </ClientWrapper>              
        </div>
         
      </body>
    </html>
  );
}
